apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heki-web
  namespace: heki
  labels:
    app: heki
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: heki.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: heki-web
                port:
                  number: 80
